export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "SIGNIN_FAILED";
//user
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";
//deletUser
export const DELETE_USER_REQUEST = "Delete_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";
//updateUser
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
//updateUser
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
//updateUser
export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED";
//getListCategory
export const GET_LIST_CATEGORY_REQUEST = "GET_LIST_CATEGORY_REQUEST";
export const GET_LIST_CATEGORY_SUCCESS = "GET_LIST_CATEGORY_SUCCESS";
export const GET_LIST_CATEGORY_FAILED = "GET_LIST_CATEGORY_FAILED";

//adcategory
export const ADD_CATEGORY_REQUEST = "ADD_AND_UPDATED_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_AND_UPDATED_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILED = "ADD_AND_UPDATED_CATEGORY_FAILED";
//deleteCategory
export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED";
//addProduct
export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";
//getProduct
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED";
//addColor
export const ADD_COLOR_REQUEST = "ADD_COLOR_REQUEST";
export const ADD_COLOR_SUCCESS = "ADD_COLOR_SUCCESS";
export const ADD_COLOR_FAILED = "ADD_COLOR_FAILED";
//getColors
export const GET_COLOR_REQUEST = "GET_COLOR_REQUEST";
export const GET_COLOR_SUCCESS = "GET_COLOR_SUCCESS";
export const GET_COLOR_FAILED = "GET_COLOR_FAILED";
//addImage
export const ADD_IMAGE_REQUEST = "ADD_IMAGE_REQUEST";
export const ADD_IMAGE_SUCCESS = "ADD_IMAGE_SUCCESS";
export const ADD_IMAGE_FAILED = "ADD_IMAGE_FAILED";
//getImage
export const GET_IMAGE_REQUEST = "GET_IMAGE_REQUEST";
export const GET_IMAGE_SUCCESS = "GET_IMAGE_SUCCESS";
export const GET_IMAGE_FAILED = "GET_IMAGE_FAILED";
//deleteProduct
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";
//deleteProduct
export const ADD_PRODUCT_TO_DISCOUNT_REQUEST =
  "ADD_PRODUCT_TO_DISCOUNT_REQUEST";
export const ADD_PRODUCT_TO_DISCOUNT_SUCCESS =
  "ADD_PRODUCT_TO_DISCOUNT_SUCCESS";
export const ADD_PRODUCT_TO_DISCOUNT_FAILURE =
  "ADD_PRODUCT_TO_DISCOUNT_FAILURE";
//deleteProduct
export const GET_DISCOUNT_LIST_REQUEST = "GET_DISCOUNT_LIST_REQUEST";
export const GET_DISCOUNT_LIST_SUCCESS = "GET_DISCOUNT_LIST_SUCCESS";
export const GET_DISCOUNT_LIST_FAILURE = "GET_DISCOUNT_LIST_FAILURE";

//deleteProduct
export const DELETE_PRODUCT_FROM_DISCOUNT_REQUEST =
  "DELETE_PRODUCT_FROM_DISCOUNT_REQUEST";
export const DELETE_PRODUCT_FROM_DISCOUNT_SUCCESS =
  "DELETE_PRODUCT_FROM_DISCOUNT_SUCCESS";
export const DELETE_PRODUCT_FROM_DISCOUNT_FAILURE =
  "DELETE_PRODUCT_FROM_DISCOUNT_FAILURE";
